# Generated by Django 5.0.dev20230201122643 on 2023-03-20 15:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_riddle_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileClass', models.IntegerField(default=0)),
                ('accommodation', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('group', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=0)),
                ('daily_points', models.IntegerField(default=0)),
                ('last_day_accessed', models.DateField(default=datetime.date.today)),
                ('last_green_area_accessed', models.DateTimeField()),
                ('last_bin_scanned', models.DateTimeField()),
                ('staffCheck', models.BooleanField(default=False)),
                ('greenCounter', models.IntegerField(default=0)),
                ('binCounter', models.IntegerField(default=0)),
                ('walkCounter', models.IntegerField(default=0)),
                ('startingLat', models.CharField(default='', max_length=100)),
                ('startingLng', models.CharField(default='', max_length=100)),
                ('finalLat', models.CharField(default='', max_length=100)),
                ('finalLng', models.CharField(default='', max_length=100)),
                ('distanceTraveled', models.CharField(default='', max_length=100)),
                ('gameCompleted', models.IntegerField(default=0)),
                ('cluesUnlocked', models.IntegerField(default=False)),
                ('riddleDone', models.BooleanField(default=False)),
                ('riddle_message_status', models.CharField(default='', max_length=100)),
                ('challenges', models.ManyToManyField(related_name='accounts', to='game.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
