# Generated by Django 5.0.dev20230201122643 on 2023-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_bin_scanned',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_green_area_accessed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
