# Generated by Django 5.0.dev20230201122643 on 2023-02-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='accommodation',
            new_name='accommodation',
        ),
    ]
