# Generated by Django 5.0.dev20230201122643 on 2023-03-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_account_last_bin_scanned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='storiesCompleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='gameCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
