# Generated by Django 5.0.dev20230201122643 on 2023-03-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
