# Generated by Django 4.1.7 on 2023-03-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_challengestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="distanceTraveled",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="account",
            name="finalLat",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="account",
            name="finalLng",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="account",
            name="startingLat",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="account",
            name="startingLng",
            field=models.CharField(default="", max_length=100),
        ),
    ]
