# Generated by Django 5.0.dev20230201122643 on 2023-03-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_challengestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeStatus',
        ),
    ]
