# Generated by Django 5.0.dev20230201122643 on 2023-03-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_story_culprit'),
        ('users', '0011_delete_challengestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.challenge')),
            ],
        ),
    ]
