# Generated by Django 5.0.dev20230201122643 on 2023-03-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_challengestatus_challengetracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cluesUnlocked',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='gameCompleted',
            field=models.IntegerField(default=0),
        ),
    ]
