# Generated by Django 5.0.dev20230201122643 on 2023-03-23 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_account_last_bin_scanned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_bin_scanned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_green_area_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
