# Generated by Django 5.0.dev20230201122643 on 2023-02-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
