# Generated by Django 4.1.7 on 2023-03-17 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeId', models.IntegerField(default=1)),
                ('challengeDesc', models.TextField(default='', max_length=400)),
                ('challengeType',
                 models.TextField(choices=[('Bin', 'Bin'), ('Green Areas', 'Green Areas'), ('Walking', 'Walking')],
                                  default='')),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('question', models.CharField(default='Question', max_length=255)),
                ('answer1', models.CharField(default='Answer 1', max_length=255)),
                ('answer2', models.CharField(default='Answer 2', max_length=255)),
                ('answer3', models.CharField(default='Answer 3', max_length=255)),
                ('answer4', models.CharField(default='Answer 4', max_length=255)),
                ('correct_answer', models.CharField(default='Correct Answer', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_number', models.IntegerField(default=1)),
                ('sprite_1',
                 models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('sprite_2',
                 models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('sprite_3',
                 models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('sprite_4',
                 models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('sprite_5',
                 models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('clue1', models.TextField(default='', max_length=1000)),
                ('clue2', models.TextField(default='', max_length=1000)),
                ('clue3', models.TextField(default='', max_length=1000)),
                ('clue4', models.TextField(default='', max_length=1000)),
                ('clue5', models.TextField(default='', max_length=1000)),
                ('clue6', models.TextField(default='', max_length=1000)),
                ('clue7', models.TextField(default='', max_length=1000)),
                ('clue8', models.TextField(default='', max_length=1000)),
                ('clue9', models.TextField(default='', max_length=1000)),
                ('clue10', models.TextField(default='', max_length=1000)),
                ('culprit',
                 models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[0-4]$')])),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('name', models.TextField(default='', max_length=30)),
                ('brief', models.TextField(default='', max_length=500)),
                ('story',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='suspects',
                                   to='game.story')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_number', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('poi_info', models.TextField(max_length=30)),
                ('challenge',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.challenge')),
            ],
        ),
    ]
