# Generated by Django 4.1.7 on 2023-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
