# Generated by Django 5.0.dev20230201122643 on 2023-03-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='clue1',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='story',
            name='clue10',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='story',
            name='clue2',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='story',
            name='clue3',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='story',
            name='clue4',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='story',
            name='clue5',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='story',
            name='clue6',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='story',
            name='clue7',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='story',
            name='clue8',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='story',
            name='clue9',
            field=models.TextField(default='', max_length=160),
        ),
    ]
