# Generated by Django 5.0.dev20230201122643 on 2023-03-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spriteCodes', models.TextField(max_length=5)),
                ('clue1', models.TextField(default='', max_length=100)),
                ('clue2', models.TextField(default='', max_length=100)),
                ('clue3', models.TextField(default='', max_length=100)),
                ('clue4', models.TextField(default='', max_length=100)),
                ('clue5', models.TextField(default='', max_length=100)),
                ('clue6', models.TextField(default='', max_length=100)),
                ('clue7', models.TextField(default='', max_length=100)),
                ('clue8', models.TextField(default='', max_length=100)),
                ('clue9', models.TextField(default='', max_length=100)),
                ('clue10', models.TextField(default='', max_length=100)),
                ('culprit', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('name', models.TextField(default='', max_length=30)),
                ('brief', models.TextField(default='', max_length=150)),
            ],
        ),
    ]
