# Generated by Django 5.0.dev20230201122643 on 2023-03-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_story_suspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='storyNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='suspect',
            name='storyNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='culprit',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='spriteCodes',
            field=models.TextField(default='', max_length=5),
        ),
    ]
