# Generated by Django 5.0.dev20230201122643 on 2023-03-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_challenge_bin_or_area_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
