# Generated by Django 5.0.dev20230201122643 on 2023-03-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_greenarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GreenArea',
        ),
    ]
