# Generated by Django 5.0.dev20230201122643 on 2023-03-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_story_storynumber_suspect_storynumber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suspect',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='storyNumber',
        ),
        migrations.AddField(
            model_name='story',
            name='sprite_codes',
            field=models.TextField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='story',
            name='story_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='suspect',
            name='story',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='game.story'),
        ),
    ]
