# Generated by Django 5.0.dev20230201122643 on 2023-03-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_suspect_options_remove_suspect_storynumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='sprite_codes',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_number',
        ),
        migrations.AlterField(
            model_name='suspect',
            name='brief',
            field=models.TextField(default='', max_length=300),
        ),
    ]
