# Generated by Django 5.0.dev20230201122643 on 2023-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_delete_greenarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('corner1lon', models.FloatField()),
                ('conrner1lat', models.FloatField()),
                ('corner2lon', models.FloatField()),
                ('conrner2lat', models.FloatField()),
                ('corner3lon', models.FloatField()),
                ('conrner3lat', models.FloatField()),
                ('corner4lon', models.FloatField()),
                ('conrner4lat', models.FloatField()),
            ],
        ),
    ]
