# Generated by Django 5.0.dev20230201122643 on 2023-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_greenarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenarea',
            name='conrner1lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='conrner2lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='conrner3lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='conrner4lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner1lon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner2lon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner3lon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner4lon',
            field=models.FloatField(default=0),
        ),
    ]
