# Generated by Django 5.0.dev20230201122643 on 2023-03-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_greenarea_conrner1lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenarea',
            old_name='conrner1lat',
            new_name='corner1lat',
        ),
        migrations.RenameField(
            model_name='greenarea',
            old_name='conrner2lat',
            new_name='corner2lat',
        ),
        migrations.RenameField(
            model_name='greenarea',
            old_name='conrner3lat',
            new_name='corner3lat',
        ),
        migrations.RenameField(
            model_name='greenarea',
            old_name='conrner4lat',
            new_name='corner4lat',
        ),
    ]
