# Generated by Django 5.0.dev20230201122643 on 2023-03-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_spritecodes_story_sprite_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='brief',
            field=models.TextField(default='', max_length=500),
        ),
    ]
