# Generated by Django 5.0.dev20230201122643 on 2023-03-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rename_conrner1lat_greenarea_corner1lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenarea',
            name='corner1lat',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner1lon',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner2lat',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner2lon',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner3lat',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner3lon',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner4lat',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='corner4lon',
            field=models.FloatField(default=0, max_length=20),
        ),
    ]
