# Generated by Django 5.0.dev20230201122643 on 2023-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_suspect_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='sprite_codes',
        ),
        migrations.AddField(
            model_name='story',
            name='sprite_1',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='story',
            name='sprite_2',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='story',
            name='sprite_3',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='story',
            name='sprite_4',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='story',
            name='sprite_5',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
