# Generated by Django 5.0.dev20230201122643 on 2023-03-09 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_story_sprite_1_alter_story_sprite_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sprite_1',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
