# Generated by Django 5.0.dev20230201122643 on 2023-03-09 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_story_culprit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='culprit',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[0-9]$')]),
        ),
    ]
