# Generated by Django 5.0.dev20230201122643 on 2023-03-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_story_clue1_alter_story_clue10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeId', models.IntegerField(default=1)),
                ('challengeDesc', models.TextField(default='', max_length=400)),
            ],
        ),
    ]
