# Generated by Django 5.0.dev20230201122643 on 2023-03-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_challenge_delete_challenege_bin_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challengeType',
            field=models.TextField(choices=[('Bin', 'Bin'), ('Green Areas', 'Green Areas'), ('Walking', 'Walking')], default=''),
        ),
    ]
