name: Django CI

on:
  push:
    branches: [ "safeMain" ]
  pull_request:
    branches: [ "safeMain" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r <(grep -Ev '^(turfpy|pip)==' requirements.txt)
    - name: Run Tests
      run: |
        python manage.py test
